Create the Intuit Registration Page.
berhanu-tarekegn/Intuit-clone pull request #2
Opened 2020-05-14 15:24 UTC by KelynPNjeri

#### What does this PR do?
- This PR contains the code for creating the `Intuit Registration Page`. 

#### How would you run this project?
- Clone the project.
- Run the `index.html` file on your browser.

2020-05-15 01:07 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved kindly implement the changes below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-15 01:07 UTC, lucasmazo32 commented on .stickler.yml
> +    config: './eslint.config'
- [ ] Kindly enable the stickler for this repo.

2020-05-15 01:07 UTC, lucasmazo32 commented on index.html
> +            </div>
- [ ] Kindly check the size of each text.

> Original
![image](https://user-images.githubusercontent.com/57414789/82000378-c9147300-961d-11ea-9ade-50a3c2b2ce10.png)

> Your page
![image](https://user-images.githubusercontent.com/57414789/82000392-d92c5280-961d-11ea-8e35-0e058049cceb.png)

2020-05-15 15:38 UTC, berhanu-tarekegn commented
@lucasmazo32 we fixed the linter issue and the font in the header section and also fixed issues raised  from morning session stand up meeting.

2020-05-16 17:46 UTC, rammazzoti2000 approved these changes
## Project Approved :rocket: :tada: 
Hello team great job, your project is approved, feel free to merge whenever you are ready.
###
Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :heavy_check_mark: Status: Approved

2020-05-17 09:31 UTC, merged